export const ADD_SUBSCRIPTION = "addSubscription";
export const REMOVE_SUBSCRIPTION = "REMOVE_SUBSCRIPTION";

export const CREATE_SUBSCRIPTION = "CREATE_SUBSCRIPTION";
export const LOAD_SUBSCRIPTIONS = "LOAD_SUBSCRIPTION";
export const UPDATE_SUBSCRIPTION = "UPDATE_SUBSCRIPTION";
export const DELETE_SUBSCRIPTION = "DELETE_SUBSCRIPTION";
