/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/subscriptions": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.subscriptions.id"];
          created_at?: parameters["rowFilter.subscriptions.created_at"];
          updated_at?: parameters["rowFilter.subscriptions.updated_at"];
          name?: parameters["rowFilter.subscriptions.name"];
          description?: parameters["rowFilter.subscriptions.description"];
          start_date?: parameters["rowFilter.subscriptions.start_date"];
          end_date?: parameters["rowFilter.subscriptions.end_date"];
          fee_recurrence?: parameters["rowFilter.subscriptions.fee_recurrence"];
          fee?: parameters["rowFilter.subscriptions.fee"];
          category?: parameters["rowFilter.subscriptions.category"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["subscriptions"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** subscriptions */
          subscriptions?: definitions["subscriptions"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.subscriptions.id"];
          created_at?: parameters["rowFilter.subscriptions.created_at"];
          updated_at?: parameters["rowFilter.subscriptions.updated_at"];
          name?: parameters["rowFilter.subscriptions.name"];
          description?: parameters["rowFilter.subscriptions.description"];
          start_date?: parameters["rowFilter.subscriptions.start_date"];
          end_date?: parameters["rowFilter.subscriptions.end_date"];
          fee_recurrence?: parameters["rowFilter.subscriptions.fee_recurrence"];
          fee?: parameters["rowFilter.subscriptions.fee"];
          category?: parameters["rowFilter.subscriptions.category"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.subscriptions.id"];
          created_at?: parameters["rowFilter.subscriptions.created_at"];
          updated_at?: parameters["rowFilter.subscriptions.updated_at"];
          name?: parameters["rowFilter.subscriptions.name"];
          description?: parameters["rowFilter.subscriptions.description"];
          start_date?: parameters["rowFilter.subscriptions.start_date"];
          end_date?: parameters["rowFilter.subscriptions.end_date"];
          fee_recurrence?: parameters["rowFilter.subscriptions.fee_recurrence"];
          fee?: parameters["rowFilter.subscriptions.fee"];
          category?: parameters["rowFilter.subscriptions.category"];
        };
        body: {
          /** subscriptions */
          subscriptions?: definitions["subscriptions"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  subscriptions: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    updated_at?: string;
    /** Format: character varying */
    name: string;
    /** Format: text */
    description?: string;
    /** Format: date */
    start_date: string;
    /** Format: date */
    end_date?: string;
    /** Format: character varying */
    fee_recurrence: string;
    /** Format: double precision */
    fee: number;
    /** Format: character varying */
    category?: string;
  };
}

export interface parameters {
  /** @description Preference */
  preferParams: "params=single-object";
  /** @description Preference */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /** @description Preference */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description subscriptions */
  "body.subscriptions": definitions["subscriptions"];
  /** Format: uuid */
  "rowFilter.subscriptions.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.subscriptions.created_at": string;
  /** Format: timestamp with time zone */
  "rowFilter.subscriptions.updated_at": string;
  /** Format: character varying */
  "rowFilter.subscriptions.name": string;
  /** Format: text */
  "rowFilter.subscriptions.description": string;
  /** Format: date */
  "rowFilter.subscriptions.start_date": string;
  /** Format: date */
  "rowFilter.subscriptions.end_date": string;
  /** Format: character varying */
  "rowFilter.subscriptions.fee_recurrence": string;
  /** Format: double precision */
  "rowFilter.subscriptions.fee": string;
  /** Format: character varying */
  "rowFilter.subscriptions.category": string;
}

export interface operations {}

export interface external {}
