-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.service_subscriptions
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    user_id uuid NOT NULL DEFAULT auth.uid(),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    service_name character varying COLLATE pg_catalog."default" NOT NULL,
    subscription_plan character varying COLLATE pg_catalog."default",
    service_category character varying COLLATE pg_catalog."default",
    billing_period character varying COLLATE pg_catalog."default" NOT NULL,
    subscription_fee double precision NOT NULL,
    CONSTRAINT service_subscriptions_pkey PRIMARY KEY (id),
    CONSTRAINT service_subscriptions_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES auth.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.service_subscriptions
    OWNER to postgres;

GRANT ALL ON TABLE public.service_subscriptions TO anon;

GRANT ALL ON TABLE public.service_subscriptions TO authenticated;

GRANT ALL ON TABLE public.service_subscriptions TO postgres;

GRANT ALL ON TABLE public.service_subscriptions TO service_role;
